udo: false

cache:
    directories:
        # We cache the install of RT.
        - $HOME/thirdparty

before_install:
    # Clone the plugins repository and get RT set up.
    - export RTHOME="$HOME/thirdparty"
    - export PLUGINS_REPO=$HOME/plugins
    - git clone git@github.com:oposs/swco-picit-rt-local.git $PLUGINS_REPO
    - $PLUGINS_REPO/bin/install-rt-for-travis-tests.sh
    # Run initial data script to populate database.
    - PERL5LIB=$PLUGINS_REPO/lib:$PLUGINS_REPO/lib/perl5:$PLUGINS_REPO/local/lib perl $PLUGINS_REPO/bin/picitInitialData.pl --setRights
    # Install the dependencies for the API service.
    - export PERL_CPANM_OPT="--notest --local-lib $RTHOME"
    - cat PERL_MODULES | xargs $RTHOME/bin/cpanm install
    # Copy the config file into place.
    - cp etc/picit-api.cfg.dist etc/picit-api.cfg

script:
    - prove -v -r xt t
